import { CATEGORY_OF, CHECKS, EXPLANATIONS, GESTURE } from "./checks/index.js";

/** The checks table for the README (between the checks markers), generated by `pnpm gen:skill`. */
export function checksTable(): string {
  return [
    "| | check | |",
    "|---|---|---|",
    ...CHECKS.map(
      (c) =>
        `| ${GESTURE[CATEGORY_OF[c.id] ?? "scope"].replace("😐", "😐&#8288;")} | \`${c.id}\` | ${c.blurb}${c.diffOnly ? " *(needs `--diff`)*" : ""} |`,
    ),
  ].join("\n");
}

/** The /lgtm skill, generated into skills/lgtm/SKILL.md by `pnpm gen:skill`. */
export function skillMarkdown(): string {
  const checkList = CHECKS.map(
    (c) => `- ${GESTURE[CATEGORY_OF[c.id] ?? "scope"]} \`${c.id}\` — ${c.blurb}\n  ${EXPLANATIONS[c.id] ?? ""}`,
  ).join("\n");
  return `---
name: lgtm
description: Run the lgtm test linter on the current branch or a path and act on its findings. Use when the user runs /lgtm, asks whether tests are any good, or asks which tests to delete or strengthen.
---

# lgtm

First run \`lgtm --diff\` (bare: it scopes to the tests you changed, the tests you added, and the tests of
implementation you changed, against the default branch), or \`lgtm <path>\` when the user named a path, without
\`--yes\`: in a non-interactive shell it only prints the plan — files, estimated cost and runtime — and exits. Tell
the user the estimate in one line. Then run the same command again with \`--yes --format json\` to actually analyse
(for example \`lgtm --diff --yes --format json\`). The two diff-only checks are asked only about blocks your change
touched, so an old test in a file you edited is never reported as a weak regression test.

\`lgtm\` is usually installed globally; in a repo that depends on it, run \`pnpm lgtm\` / \`npx lgtm\` instead.
If neither works, do not work around it — tell the user to run \`npm i -g @stardeckai/lgtm && lgtm init\` and stop there.

For each finding: read the test, then decide **keep**, **delete** or **replace**.

- Keep it only if you can complete "this test prevents us from shipping [specific incorrect behavior]".
- Delete it when the behavior it claims to protect is already covered, or when nothing plausible would break it.
- Replace it when the behavior matters but the test does not check it. A replacement counts only once you
  have shown it fail on the plausible bug — mutate or revert the behavior, watch it go red for the right
  reason, then restore.
- Never mock the seam under test. If both sides of a boundary are faked to agree, the test proves nothing.
- Prefer one wider test with real collaborators that retires several unit tests over patching each unit
  test in place. A good audit improves the suite while reducing the test count.

Report as a table: file:line, check id, verdict, one-line reason.

## Reading the output

Each finding line opens with one of four faces, one per family: \`😐🤏\` the assertion proves this much,
\`😐👏\` you tested the mock, \`😐🤌\` what exactly are we doing here, \`😐🫸\` do not merge this. Then the
check id, its probability and a one-line reason; \`--format json\` adds a \`checks\` map with the longer explanation
and the fix, once per check. Colour is severity (red ≥ 0.9, yellow at or over the check's threshold, dim for
\`--verbose\` suspects shown with a bare \`😐\`). The verdict is one line: \`😐👍  N tests. fine. allegedly.\` or
\`😐🫵  N tests prove nothing.\` The class line counts contract-integration (the good kind), mocked-seam and pure-logic.

## Checks

${checkList}
`;
}

/** The /actually-test skill, generated into skills/actually-test/SKILL.md by `pnpm gen:skill`. */
export function actuallyTestMarkdown(): string {
  return `---
name: actually-test
description: Write the tests a change actually needs, then iterate with lgtm until they prove something. Use when the user runs /actually-test or asks to test what was just built.
---

# actually-test

Goal: a test for every applicable flow and edge case of the code you just built, each one red for the realistic
bug, then iterate on \`/lgtm\` until it passes.

## 1. Inventory

Write this down before writing a single test.

- The entry points the change touched.
- Every seam it crosses: one component writes and another reads, producer and consumer, auth, persistence,
  cache keys, queues, serialization.
- Every refusal path the code exists for: permissions, tenant isolation, duplicates, quotas, stale versions,
  concurrency, partial failure, invalid input.
- The true external edges: clock, randomness, network, third-party SDKs, filesystem.

## 2. Choose

- Few wide tests with real collaborators beat many mocked units.
- Fake only the external edges from the inventory. Nothing first-party.
- Every seam gets at least one test with both sides real, asserting they agree.
- Every refusal path gets one test that drives it and asserts the refusal.
- Skip trivial primitives. Any feature test that uses them covers them.
- For each test, finish "this test prevents us from shipping [specific incorrect behavior]". If you cannot, do
  not write it.

## 3. Write and run

Build fixtures through the real constructors and validators. Assert exact values on the fields that define
correctness. Await everything, including rejections and background work. No retries. Run the suite green.

## 4. Prove red

For each test that guards a refusal path or a fix: break the behaviour on purpose, run that test, watch it fail
for the right reason, restore. A test you never saw fail is not a test.

## 5. Iterate with lgtm

1. \`lgtm --diff\` with no \`--yes\`, read the plan, tell the user the estimate in one line.
2. \`lgtm --diff --yes --format json\`.
3. For each finding decide keep, delete or replace exactly as the \`/lgtm\` skill says.
4. Re-run until the verdict is \`😐👍\` or every remaining finding has a one-line defence.

Cap it at three rounds and report what is left.

## 6. Report

A table: flow or edge case, test name, the bug it prevents, the lgtm verdict. Then the remaining findings with
their defences. Then anything you chose not to test, and why.

## Do not

- Do not let \`toHaveBeenCalled\` be the only evidence.
- Do not mock the seam under test.
- Do not compute an expected value with production code.
- Do not snapshot whole objects.
- Do not write a test for the sake of coverage.
`;
}

/** Every bundled skill, in the order they are written. */
export const SKILLS: { name: string; markdown: () => string }[] = [
  { name: "lgtm", markdown: skillMarkdown },
  { name: "actually-test", markdown: actuallyTestMarkdown },
];
