import { CATEGORY_OF, CHECKS, EXPLANATIONS, GESTURE } from "./checks/index.js";

/** The checks table for the README (between the checks markers), generated by `pnpm gen:skill`. */
export function checksTable(): string {
  return [
    "| | check | |",
    "|---|---|---|",
    ...CHECKS.map(
      (c) =>
        `| ${GESTURE[CATEGORY_OF[c.id] ?? "scope"].replace("😐", "😐&#8288;")} | \`${c.id}\` | ${c.blurb}${c.diffOnly ? " *(needs `--diff`)*" : ""} |`,
    ),
  ].join("\n");
}

/** The /lgtm skill, generated into skills/lgtm/SKILL.md by `pnpm gen:skill`. */
export function skillMarkdown(): string {
  const checkList = CHECKS.map(
    (c) => `- ${GESTURE[CATEGORY_OF[c.id] ?? "scope"]} \`${c.id}\` — ${c.blurb}\n  ${EXPLANATIONS[c.id] ?? ""}`,
  ).join("\n");
  return `---
name: lgtm
description: Run the lgtm test linter on the current branch or a path and act on its findings. Use when the user runs /lgtm, asks whether tests are any good, or asks which tests to delete or strengthen.
---

# lgtm

First run \`lgtm --diff\` (bare: it scopes to the tests you changed, the tests you added, and the tests of
implementation you changed, against the default branch), or \`lgtm <path>\` when the user named a path, without
\`--yes\`: in a non-interactive shell it only prints the plan — files, estimated cost and runtime — and exits. Tell
the user the estimate in one line. Then run the same command again with \`--yes --format json\` to actually analyse
(for example \`lgtm --diff --yes --format json\`). The two diff-only checks are asked only about blocks your change
touched, so an old test in a file you edited is never reported as a weak regression test.

\`lgtm\` is usually installed globally; in a repo that depends on it, run \`pnpm lgtm\` / \`npx lgtm\` instead.
If neither works, do not work around it — tell the user to run \`npm i -g @stardeckai/lgtm && lgtm init\` and stop there.

For each finding: read the test, then decide **keep**, **delete** or **replace**.

- Keep it only if you can complete "this test prevents us from shipping [specific incorrect behavior]".
- Delete it when the behavior it claims to protect is already covered, or when nothing plausible would break it.
- Replace it when the behavior matters but the test does not check it. A replacement counts only once you
  have shown it fail on the plausible bug — mutate or revert the behavior, watch it go red for the right
  reason, then restore.
- Never mock the seam under test. If both sides of a boundary are faked to agree, the test proves nothing.
- Prefer one wider test with real collaborators that retires several unit tests over patching each unit
  test in place. A good audit improves the suite while reducing the test count.

Report as a table: file:line, check id, verdict, one-line reason.

## Reading the output

Each finding line opens with one of four faces, one per family: \`😐🤏\` the assertion proves this much,
\`😐👏\` you tested the mock, \`😐🤌\` what exactly are we doing here, \`😐🫸\` do not merge this. Then the
check id, its probability and a one-line reason; \`--format json\` adds a \`checks\` map with the longer explanation
and the fix, once per check. Colour is severity (red ≥ 0.9, yellow at or over the check's threshold, dim for
\`--verbose\` suspects shown with a bare \`😐\`). The verdict is one line: \`😐👍  N tests. fine. allegedly.\` or
\`😐🫵  N tests prove nothing.\` The class line counts contract-integration (the good kind), mocked-seam and pure-logic.

## Checks

${checkList}
`;
}
